services:
  postgres:
    image: "postgres"
#    environment:
#      POSTGRES_USER: vuw589
#      POSTGRES_PASSWORD: Admin2024
#      POSTGRES_DB: metabase
    volumes:
      - /var/lib/postgresql/data/:/var/lib/postgresql/data/
  web:
    image: "ghcr.io/arcatva/bhakti-lounge:latest"
    depends_on:
      - postgres
    environment:
      PROFILE: PRODUCTION
  metabase:
    image: "metabase/metabase"
    depends_on:
      - postgres
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: vuw589
      MB_DB_PASS: Admin2024
      MB_DB_HOST: postgres
  nginx:
    image: "nginx"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - metabase
    volumes:
      - /etc/nginx/conf.d/:/etc/nginx/conf.d/
      # bind host nginx configuration to container, template defined in project's /conf/nginx/nginx.conf
      - /etc/nginx/ssl:/etc/nginx/ssl/