name: Deploy ASP.NET Application

on:
  repository_dispatch:
    types: [package-pushed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Copy docker-compose.yml using password
      env:
        SSH_HOST: ${{ secrets.HOST_IP }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r ./docker-compose.yml root@$SSH_HOST:/root/
        sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r ./conf/nginx/conf.d/default.conf root@$SSH_HOST:/etc/nginx/conf.d/default.conf
        
    - name: Deploy to Server
      env:
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        MB_DB_TYPE: ${{ secrets.MB_DB_TYPE }}
        MB_DB_DBNAME: ${{ secrets.MB_DB_DBNAME }}
        MB_DB_PORT: ${{ secrets.MB_DB_PORT }}
        MB_DB_USER: ${{ secrets.MB_DB_USER }}
        MB_DB_PASS: ${{ secrets.MB_DB_PASS }}
        MB_DB_HOST: ${{ secrets.MB_DB_HOST }}
        SSH_HOST: ${{ secrets.HOST_IP }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        PROD_DSN: ${{ secrets.PROD_DSN }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SSH_HOST '
          export POSTGRES_DB=$POSTGRES_DB
          export POSTGRES_PASSWORD=$POSTGRES_PASSWORD
          export POSTGRES_USER=$POSTGRES_USER
          export MB_DB_TYPE=$MB_DB_TYPE
          export MB_DB_DBNAME=$MB_DB_DBNAME
          export MB_DB_PORT=$MB_DB_PORT
          export MB_DB_USER=$MB_DB_USER
          export MB_DB_PASS=$MB_DB_PASS
          export MB_DB_HOST=$MB_DB_HOST
          export PROD_DSN=$PROD_DSN
          echo $POSTGRES_USER
          cd /root/
          docker compose pull
          docker compose up -d
        '
