name: Deploy ASP.NET Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Copy docker-compose.yml using password
      env:
        SSH_HOST: ${{ secrets.HOST_IP }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r ./docker-compose.yml root@$SSH_HOST:/root/
        
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.HOST_IP }} '
          export PROD_DSN=${{ secrets.PROD_DSN }}
          cd /root/
          docker-compose pull
          docker-compose up -d
        '
